// Module 5 - Performing Diagnostic and Root Cause Analysis
// Demo 2 - Using Autocluster

// Connect to the sample database
#connect cluster('help.kusto.windows.net').database('Samples')

//  autocluster() to find interesting clusters during the 2 minutes of the spike
let min_peak_t=datetime(2016-08-23 15:00);
let max_peak_t=datetime(2016-08-23 15:02);
demo_clustering1
  | where PreciseTimeStamp between(min_peak_t..max_peak_t)
  | evaluate autocluster()
